KakaoBrain Custom Resnet9 || CIFAR10 || Kakao Brain
stanford-futuredata/dawn-bench-entries pull request #113
Opened 2019-10-15 01:46 UTC by wbaek

We updated the training and inference recodes

2019-10-22 16:22 UTC, codyaustun requested changes
Looks good overall, but the date seems wrong.

2019-10-22 16:22 UTC, codyaustun commented on CIFAR10/train/kakaobrain_custom-resnet9_4v100-braincloud_pytorch.json
> +    "timestamp": "2019-08-22",
I can't verify this date. Please change to the date this PR was submitted.

2019-10-22 16:22 UTC, codyaustun commented on CIFAR10/inference/kakaobrain_custom-resnet9_1v100-braincloud_pytorch_inference.json
> +    "timestamp": "2019-08-22",
I can't verify this date. Please change to the date this PR was submitted.

2019-10-23 04:44 UTC, wbaek commented
@codyaustun  we have updated timestamps.

2019-10-23 15:54 UTC, codyaustun commented
Looks good to me!

2019-10-23 15:55 UTC, merged