Custom Resnet9 || CIFAR10 || Apple
stanford-futuredata/dawn-bench-entries pull request #122
Opened 2019-12-12 00:55 UTC by tiagoakle

2019-12-19 21:41 UTC, tiagoakle commented
Hi @codyaustun anything I can do to help?

2019-12-21 05:20 UTC, codyaustun requested changes

2019-12-21 05:20 UTC, codyaustun commented on CIFAR10/train/apple_resnet9_8v100_pytorch.json
> +    "misc": {}
Can you add details about your training routine (e.g., learning rate schedule, batch size, optimizer, etc.) and versions for any other important libraries (e.g., Cuda)? For example, take a look at [David Page's original submission](https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/CIFAR10/train/davidcpage_resnet9_1v100-ec2_pytorch.json).

2019-12-21 05:20 UTC, codyaustun commented on CIFAR10/train/apple_resnet9_8v100_pytorch.json
> +    "codeURL": "https://github.com/apple/ml-cifar-10-faster",
Please specify the commit hash either in the `codeURL` or as a separate `commitHash` field

2019-12-21 05:22 UTC, codyaustun commented
> Hi @codyaustun anything I can do to help?

Sorry for the delay! Overall the submission looks good, but it would be nice to add more information to the JSON file.

2020-01-07 21:28 UTC, tiagoakle commented
I think this addresses the comments

2020-01-08 14:57 UTC, codyaustun approved these changes
Thanks! Looks good to me!

2020-01-08 14:57 UTC, merged