Intel(R) Optimized Caffe Training on AWS c5.18xlarge
stanford-futuredata/dawn-bench-entries pull request #17
Opened 2018-04-19 07:41 UTC by daisyden

The test is performed on 64 AWS c5.18xlarge nodes. Achieved top-5 accuracy 0.9307 within 6.17 hours with Resnet50. Please find the README.md and "Guide to Launch Intel Caffe Multi Nodes Training on AWS.docx" under https://github.com/intel/caffe/blob/DAWN_Bench for detailed steps to reproduce the result.

2018-04-19 16:01 UTC, codyaustun requested changes
Minor issues, but overall looks good.

2018-04-19 16:01 UTC, codyaustun commented on ImageNet/train/Intel_Resnet50_ec2_Xeon_8124M_intelcaffe.json
> +    "misc": {
Can you add one more field to `misc` with a description of the communication method you used? Even a link to https://github.com/intel/caffe/wiki/Multinode-guide#communication from your README would be fine.

2018-04-19 16:01 UTC, codyaustun commented on ImageNet/train/Intel_Resnet50_ec2_Xeon_8124M_intelcaffe.json
> +        "warmUp": "the learning rate starts at 0.1, then it increases linearly per iteration for the first 5 epochs",
You say you do a 5 epoch warm up here, but the schedule you have below looks like it only has 3 epochs for the warm up. Please update to make them consistent. Specifically, I think the 5 epochs here should be 3 to match the length of your TSV.

2018-04-20 01:03 UTC, daisyden commented
@codyaustun I have updated according to your comments. Thanks a lot!

2018-04-20 02:29 UTC, codyaustun approved these changes

2018-04-20 02:30 UTC, merged