ResNet18 || CIFAR10 || bkj
stanford-futuredata/dawn-bench-entries pull request #29
Opened 2018-04-21 00:28 UTC by bkj

2018-04-21 15:50 UTC, codyaustun requested changes

2018-04-21 15:50 UTC, codyaustun commented on CIFAR10/train/basenet.json
> +    "misc": {
What hyperparameters did you use? Please add the following information to `misc`:

- learning rate schedule
- batch size
- optimizer
- momentum
- weight decay

The [Google ResNet50 submission](https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/ImageNet/train/google_resnet50_tpu_tensorflow18.json) is a good example for reference.

2018-04-21 15:50 UTC, codyaustun commented on CIFAR10/train/basenet.json
> +    "codeURL": "https://github.com/bkj/basenet/tree/49b2b61e5b9420815c64227c5a10233267c1fb14/examples",
Please add the command line or instructions on how to reproduce your experiment to a README for this directory or add a `commandLine` field under `misc`

2018-04-21 15:50 UTC, codyaustun commented on CIFAR10/train/basenet.json
> +    "framework": "pytorch",
What version of PyTorch did you use? Please update with the version number or git commit hash.

2018-04-21 16:18 UTC, bkj commented on CIFAR10/train/basenet.json
> +    "framework": "pytorch",
fixed

2018-04-21 16:21 UTC, bkj commented on CIFAR10/train/basenet.json
> +    "misc": {
added hyperparams

2018-04-22 14:20 UTC, codyaustun approved these changes

2018-04-22 14:22 UTC, merged