KResNet34 || CIFAR10 || chen
stanford-futuredata/dawn-bench-entries pull request #33
Opened 2018-04-21 02:37 UTC by wang-chen

2018-04-21 16:05 UTC, codyaustun requested changes

2018-04-21 16:05 UTC, codyaustun commented on CIFAR10/train/KRes34_1GTX1080Ti_pytorch.json
> +    "costPerHour": "NA",
If you're not submitting to cost, remove this field.

2018-04-21 16:05 UTC, codyaustun commented on CIFAR10/train/KRes34_1GTX1080Ti_pytorch.json
> +    "framework": "PyTorch",
What version of PyTorch did you use? Please at the version number or git commit hash.

2018-04-21 16:05 UTC, codyaustun commented on CIFAR10/train/KRes34_1GTX1080Ti_pytorch.json
> +        "CUDA version": "8.0"
What hyperparameters did you use? Please add the following information to `misc`:

- learning rate schedule
- batch size
- optimizer
- momentum
- weight decay

The [Google ResNet50 submission](https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/ImageNet/train/google_resnet50_tpu_tensorflow18.json) is a good example for reference.

2018-04-21 16:05 UTC, codyaustun commented on CIFAR10/train/KRes34_1GTX1080Ti_pytorch.json
> +    "codeURL": "https://github.com/wang-chen/KervNets",
Please include the commit hash in the URL or add an extra field to `misc`.

2018-04-22 04:33 UTC, wang-chen commented
Thanks for your time, I have added the details following your comments.

2018-04-22 15:03 UTC, codyaustun requested changes

2018-04-22 15:03 UTC, codyaustun commented on CIFAR10/train/KRes34_1GTX1080Ti_pytorch.json
> +    	"MultiStepLR_Milestones": "[50,100,150]",
Please remove the `LR`, `MultiStepLR_Milestones`, and `MultiStepLR_Gamma` fields and express the learning rate schedule using the format below:

```
misc: {
  ...
  schedule: [
    {"learning_rate": 0.1, "epochs": 50},
    {"learning_rate": 0.01, "epochs": 50},
    {"learning_rate": 0.001, "epochs": 50},
    {"learning_rate": 0.0001, "epochs": 50},
  ]
}
```

2018-04-22 15:30 UTC, wang-chen commented
Thanks for your time. It has been changed accordingly.

2018-04-22 22:08 UTC, codyaustun approved these changes

2018-04-22 22:08 UTC, merged