resnet 50 || imagenet || fast.ai + students
stanford-futuredata/dawn-bench-entries pull request #35
Opened 2018-04-21 05:51 UTC by jph00

Updated run with different hyperparams.

2018-04-21 06:28 UTC, brettkoonce commented
🍀

2018-04-21 16:14 UTC, codyaustun requested changes

2018-04-21 16:14 UTC, codyaustun commented on ImageNet/train/fastai_pytorch.json
> +    "misc": {
What hyperparameters did you use?  Please add the following information to `misc`:

- learning rate schedule
- batch size
- optimizer
- momentum
- weight decay

The [Google ResNet50 submission](https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/ImageNet/train/google_resnet50_tpu_tensorflow18.json) is a good example for reference.

2018-04-21 16:14 UTC, codyaustun commented on ImageNet/train/fastai_pytorch.json
> +    "codeURL": "https://github.com/fastai/imagenet-fast/blob/1bc5aeec765572397c0ebe4a5d616d03beeeeec1/aws/do_nosh.sh",
This URL gives a 404 Error. Please correct.

2018-04-21 18:12 UTC, jph00 commented
@codyaustun - fixed now. Sorry about the incorrect URL! In addition to the hyperparams you requested, I also added the communications backend details to the 'misc' section (note that NCCL 2 isn't open sourced by Nvidia any more so I can't provide a code link for that one.)

2018-04-21 22:05 UTC, bignamehyp commented
Did you use the [blacklisted](https://da-data.blogspot.com/2016/02/cleaning-imagenet-dataset-collected.html) validation set?
https://github.com/fastai/imagenet-fast/blob/master/imagenet_nv/blacklist.sh

2018-04-21 23:48 UTC, jph00 commented
We removed those files as discussed by the devkit notes for the imagenet competition - you've linked to something that claims maybe that it may not the right thing to do, but I believe that the imagenet devkit is fairly clear to the contrary.

(It does mention that the reason for the blacklist was the presence of incorrect bounding boxes, but it does not go on to say to use the blacklisted images for classification models.)

(It would have been better if this was addressed explicitly in the competition rules of course because optimal hyperparams are different depending on whether you do this or not. If different entries are using different approaches then they won't be exactly comparable.)

2018-04-24 17:55 UTC, codyaustun approved these changes

2018-04-24 17:59 UTC, codyaustun commented
@jph00 @bignamehyp Aside from the blacklist issue, this pull request looks good to me. Once we decide on the blacklist examples in [issue #36](https://github.com/stanford-futuredata/dawn-bench-entries/issues/36), we will update this submission with the relevant information/fields.

2018-04-24 18:00 UTC, merged

2018-04-25 00:58 UTC, jgong5 commented
Is this submission using the blacklisted validation set? Then that would not be an apple-to-apple comparison if other teams are not using the same validation set.