add k80/v100 ec2 squad DrQA entries
stanford-futuredata/dawn-bench-entries pull request #57
Opened 2018-09-30 06:35 UTC by brettkoonce

submitted matching pr upstream: https://github.com/hitvoice/DrQA/pull/20

2018-10-03 03:23 UTC, codyaustun requested changes
Looks good overall. I just need a few more details to verify costPerHour

2018-10-03 03:23 UTC, codyaustun commented on SQuAD/train/dawn_drqa_1k80-ec2.json
> +    "costPerHour": 0.900,
Where is this `costPerHour` coming from? What cloud service did you use?

2018-10-03 03:23 UTC, codyaustun commented on SQuAD/train/dawn_drqa_1p100-ec2.json
> +    "costPerHour": 3.06,
Where is this `costPerHour` coming from? What cloud service did you use?

2018-10-03 03:23 UTC, codyaustun commented on SQuAD/train/dawn_drqa_1k80-ec2.json
> +    "misc": {
For convenience, can you add hyperparameters like batch size, optimizer, learning rate schedule, and dropout rate to `misc`?

2018-10-03 03:23 UTC, codyaustun commented on SQuAD/train/dawn_drqa_1nv1070ti-dev.json
> +      "paper_link": "http://www-cs.stanford.edu/people/danqi/papers/acl2017.pdf"
For convenience, can you add hyperparameters like batch size, optimizer, learning rate schedule, and dropout rate to `misc`?

2018-10-03 03:23 UTC, codyaustun commented on SQuAD/train/dawn_drqa_1p100-ec2.json
> +      "paper_link": "http://www-cs.stanford.edu/people/danqi/papers/acl2017.pdf"
For convenience, can you add hyperparameters like batch size, optimizer, learning rate schedule, and dropout rate to `misc`?

2018-10-03 05:17 UTC, brettkoonce commented on SQuAD/train/dawn_drqa_1k80-ec2.json
> +    "costPerHour": 0.900,
p2 on ec2, I can tag it better!

2018-10-03 05:18 UTC, brettkoonce commented on SQuAD/train/dawn_drqa_1p100-ec2.json
> +    "costPerHour": 3.06,
p3 on ec2, will tag it better!

2018-10-03 05:48 UTC, brettkoonce commented on SQuAD/train/dawn_drqa_1k80-ec2.json
> +    "misc": {
Going to double-check all of these, let me chat w/ Runqi!

2018-10-03 11:06 UTC, brettkoonce commented on SQuAD/train/dawn_drqa_1k80-ec2.json
> +    "misc": {
@codyaustun updated, let me know if you need anything else!

2018-10-03 14:53 UTC, codyaustun approved these changes

2018-10-03 14:53 UTC, codyaustun commented
Thanks! Looks good to me

2018-10-03 14:56 UTC, merged

2018-10-03 15:19 UTC, brettkoonce commented
Thanks @codyaustun!

2018-10-03 17:27 UTC, hitvoice commented
@codyaustun A crucial question: which version of the SQuAD dataset is used for the question answering leaderboard now, 1.0 or 2.0?  The hyperlink [https://rajpurkar.github.io/SQuAD-explorer/](https://rajpurkar.github.io/SQuAD-explorer/) on the page led to 1.0 before but leads to 2.0 now and I haven't found any explicit instructions. The SQuAD 2.0 dataset is much more difficult and the results will vary a lot.

2018-10-15 01:53 UTC, codyaustun commented
@hitvoice for the purposes of rolling submissions, we will continue to use the SQuAD 1.0 dataset. If we introduce a new version of the benchmark, we would update the tasks to the most relevant dataset at the time.

2018-10-15 09:11 UTC, hitvoice commented
@codyaustun Got it. Thanks for the explanation!