ResNet-50 || ImageNet Training || ModelArts Service of Huawei Cloud
stanford-futuredata/dawn-bench-entries pull request #62
Opened 2018-11-26 08:49 UTC by sleepfin

ResNet-50 trained on 128 Tesla-V100 GPUs

This code was run on ModelArts Service of Huawei Cloud using 16 nodes (8*V100 for each node) with RDMA.
MoXing is a cloud-native, high-performace and easy-to-use deep learning framework built upon TensorFlow, MXNet and PyTorch. Document can be found [HERE](https://support.huaweicloud.com/en-us/usermanual-dls/dls_01_0046.html)
The framework is TensorFlow v1.8.0.
Please let me know if you have any questions!

2018-11-27 21:08 UTC, codyaustun requested changes

2018-11-27 21:08 UTC, codyaustun commented on ImageNet/train/huaweicloud_resnet50_modelarts_16_machine_tensorflow18.json
> +    "codeURL": "https://github.com/huawei-clouds/modelarts-example/blob/master/ImageNet-10min/fast_imagenet_dym_node_16.py",
Can you add the commit hash either to the `codeURL` or as a separate `commitHash` field?

2018-11-27 21:08 UTC, codyaustun commented on ImageNet/train/huaweicloud_resnet50_modelarts_16_machine_tensorflow18.json
> +        "model implementation": "https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_v1.py",
Please add the commit hash for the model.

2018-11-27 21:08 UTC, codyaustun commented on ImageNet/train/huaweicloud_resnet50_modelarts_16_machine_tensorflow18.json
> +        "backend": "8*Tesla-V100 + CUDA-9.0 + CuDNN-7.0.5",
Please split this into separate fields:

```suggestion
        "backend": "16 nodes (8*V100 for each node)",
        "CUDA version": "9.0",
        "CuDNN version": "7.0.2"
```

2018-11-27 21:08 UTC, codyaustun commented on ImageNet/train/huaweicloud_resnet50_modelarts_16_machine_tensorflow18.json
> +    "hardware": "modelarts",
This would be clearer as follows:

```suggestion
    "hardware": "16 nodes (8*V100 for each node)",
```

2018-11-27 21:09 UTC, codyaustun commented
Looks good overall. Just some minor changes.

2018-11-29 09:23 UTC, sleepfin commented
@codyaustun Thanks for the reply. I have submitted the changes as required. Pls check again.

2018-11-29 21:30 UTC, codyaustun approved these changes

2018-11-29 21:34 UTC, merged