ResNet-50 || ImageNet Inference || Perseus AI Cloud Acceleration team in Alibaba Cloud
stanford-futuredata/dawn-bench-entries pull request #66
Opened 2018-12-12 15:21 UTC by ShaohuaWu2018

Alibaba Cloud submissions for ImageNet inference with resnet50 on ecs.gn5i-c8g1.2xlarge

2018-12-17 19:25 UTC, codyaustun requested changes
Looks good overall. Just a few minor changes.

2018-12-17 19:25 UTC, codyaustun commented on ImageNet/inference/AlibabaCloud_resnet50_1p4_ecs_tensorflow.json
> +    "framework": "TensorFlow",
Please include TensorFlow version number.

2018-12-17 19:25 UTC, codyaustun commented on ImageNet/inference/AlibabaCloud_resnet50_1p4_ecs_tensorflow.json
> +    "codeURL": "https://github.com/ali-perseus/DAWNBench_Inference",
Can you add the commit hash either to the `codeURL` or as a separate `commitHash` field?

2018-12-18 02:17 UTC, ShaohuaWu2018 commented on ImageNet/inference/AlibabaCloud_resnet50_1p4_ecs_tensorflow.json
> +    "framework": "TensorFlow",
Thanks for your kindness and great efforts on this PR. The version number will be added.

2018-12-18 02:21 UTC, ShaohuaWu2018 commented on ImageNet/inference/AlibabaCloud_resnet50_1p4_ecs_tensorflow.json
> +    "codeURL": "https://github.com/ali-perseus/DAWNBench_Inference",
Thanks, I will add a separate commitHash field to include commit hash.

2018-12-18 04:56 UTC, ShaohuaWu2018 commented
The tensorflow version number and commit hash for DAWNBench_Inference code have been added. Thank you for your time and looking forward to your response.

2018-12-18 16:06 UTC, codyaustun approved these changes

2018-12-18 16:06 UTC, codyaustun commented
Thanks! Looks good to me.

2018-12-18 17:59 UTC, codyaustun commented
Actually, I have one more question. Can you point me to pricing information for Alibaba Cloud? I just want to double check that the cost field is correct.

2018-12-19 03:17 UTC, ShaohuaWu2018 commented
Thanks! I am pleased to make an introduction to show how to get the price information from web site of Alibaba Cloud.

2018-12-20 08:16 UTC, ShaohuaWu2018 commented
Here is the link to show the price for Alibaba Cloud instances: 
https://cn.aliyun.com/price/product?spm=5176.8789780.1092586.1.2d0257a8rKsPw1#/ecs/detail

On this website, please scroll down and find the instance with the name of "ecs.gn5i-c8g1.2xlarge".
You will see there are 9 columns, and the price of on-demand is shown in the fourth column.

I am so sorry that the price page is in Chinese. I have made a translation for the titles of all these 9 columns as below, 
Column 1: vCPU
Column 2: Type of instances.
Column 3: Memory.
Column 4: On-demand price (per hour).
Column 5: Monthly price.
Column 6: Monthly reduced price.
Column 7: Yearly price.
Column 8: Monthly price for 3 years.
Column 9: Monthly price for 5 years.

Please note: the price listed is in Chinese Yuan (CNY), please convert it to US dollar by an exchange rate of 0.15 that is the rate we checked on 2018-12-12, the day of this submission. 

For any questions, please do not hesitate to contact me. Thanks.

2018-12-25 04:21 UTC, codyaustun commented
Great! That looks correct.  ((1000 * 3600) / 4.218 ) * 1.54e-06 / 0.15 is roughly 8.75 CNY. Thanks for the link and translation!

2018-12-25 04:22 UTC, merged