ResNet18||CIFAR10 Inference time|| Baidu-USA-GAIT
stanford-futuredata/dawn-bench-entries pull request #76
Opened 2019-02-02 20:34 UTC by BAIDU-USA-GAIT-LEOPARD

we update the Json file, please only review the latest pull request.

2019-02-04 19:02 UTC, codyaustun requested changes
@BAIDU-USA-GAIT-LEOPARD I'll finish reviewing this PR once the file extension is fixed and the unit tests pass.

2019-02-04 19:02 UTC, codyaustun commented on CIFAR10/inference/BAIDU-USA-GAIT_ResNet18_1GTX1080_pytorch.json
> +	    "author": Baidu USA GAIT LEOPARD team: Baopu Li, Jiazhuo Wang, Zhiyu Cheng, Haofeng Kou, Yingze Bao
This is not valid JSON. Please fix and make sure the unit tests pass. From the root directory of this repo, you can run the unittests locally with the following:

```
pip install -r requirements.txt
pytest
```

2019-02-06 20:00 UTC, codyaustun commented
@BAIDU-USA-GAIT-LEOPARD it looks like you deleted the JSON file. Should I close this PR and only review #77 ?

2019-02-06 20:02 UTC, BAIDU-USA-GAIT-LEOPARD commented
> @BAIDU-USA-GAIT-LEOPARD it looks like you deleted the JSON file. Should I close this PR and only review #77 ?

Yes please and thanks.

2019-02-06 20:03 UTC, closed without merging