add FastFusionNet results
stanford-futuredata/dawn-bench-entries pull request #79
Opened 2019-03-02 17:01 UTC by felixgwu

2019-03-05 19:07 UTC, codyaustun requested changes
Looks good overall. I requested some minor changes.

2019-03-05 19:07 UTC, codyaustun commented on SQuAD/inference/dawn_fastfusionnet-1080ti.json
> +    "codeURL": "https://github.com/felixgwu/FastFusionNet",
Please specify the commit hash either in the `codeURL` or as a separate `commitHash` field

2019-03-05 19:07 UTC, codyaustun commented on SQuAD/train/dawn_fastfusionnet-1080ti.json
> +    "codeURL": "https://github.com/felixgwu/FastFusionNet",
Same as above. Please specify the commit hash either in the `codeURL` or as a separate `commitHash` field

2019-03-05 19:07 UTC, codyaustun commented on SQuAD/inference/dawn_fastfusionnet-1080ti.json
> +    "codeURL": "https://github.com/felixgwu/FastFusionNet",
Also looking at the repo, I see that you have instructions for training. Can you also include instructions for inference?

2019-03-07 06:27 UTC, felixgwu commented on SQuAD/train/dawn_fastfusionnet-1080ti.json
> +    "codeURL": "https://github.com/felixgwu/FastFusionNet",
Done.

2019-03-07 06:28 UTC, felixgwu commented on SQuAD/inference/dawn_fastfusionnet-1080ti.json
> +    "codeURL": "https://github.com/felixgwu/FastFusionNet",
I've added commitHash and the instructions for inference. Thanks!

2019-03-07 06:31 UTC, felixgwu commented
Hi @codyaustun, the commitHash and the inference instructions have been added.
Is there anything else you want to add?

2019-03-09 18:52 UTC, codyaustun commented
Looks good to me!

2019-03-09 18:52 UTC, codyaustun approved these changes

2019-03-09 18:52 UTC, merged

2019-03-09 20:33 UTC, felixgwu commented
Thanks!

2019-03-09 20:45 UTC, felixgwu commented
Hi @codyaustun 
It looks like there is a bug when processing the tsv file.
It uses the training time after the first epoch instead of the the time spent after the 4th epoch (when the model gets F1 75).

![image](https://user-images.githubusercontent.com/7753366/54077098-f202e080-4281-11e9-87fb-5b0ab4730460.png)

2019-03-09 21:22 UTC, codyaustun commented
@felixgwu good catch! The f1Score column should be [0, 1] not [0, 100]. Can you please fix and submit a pull request?

2019-03-09 22:01 UTC, felixgwu commented
@codyaustun 
Since I've deleted my old fork, I create a new pull request here instead: https://github.com/stanford-futuredata/dawn-bench-entries/pull/81