ResNet-50 || ImageNet Training || ModelArts Service of Huawei Cloud
stanford-futuredata/dawn-bench-entries pull request #82
Opened 2019-03-13 03:16 UTC by sleepfin

ResNet-50 trained on 128 Tesla-V100 GPUs version 2.0

This version of ImageNet training job is an upgrade to the previous version. We have successfully reduced the training time from 10 minutes to less than 5 minutes. All scripts were executed on ModelArts Service of Huawei Cloud using 16 nodes with GDR (8*V100 with NVLink for each node).

MoXing is a cloud-native, high-performace and easy-to-use deep learning framework built upon TensorFlow, MXNet and PyTorch. Document can be found [HERE](https://github.com/huawei-clouds/modelarts-example/tree/master/moxing-apidoc)
The framework is TensorFlow v1.8.0. horovod is also used.

URL of training codes and model implementation will be uploaded soon. Please let me know if you have any questions!

2019-03-17 18:46 UTC, codyaustun requested changes
Looks good overall. Just 1 comment

2019-03-17 18:46 UTC, codyaustun commented on ImageNet/train/huaweicloud_resnet50_modelarts_16_machine_tensorflow18.json
> +    "codeURL": "will be uploaded soon",
Just remove this field until you can provide the updated code.

2019-03-18 05:43 UTC, sleepfin commented
@codyaustun I have removed codeURL for now. Please check again

2019-03-18 23:51 UTC, codyaustun approved these changes

2019-03-18 23:52 UTC, merged